spring:
  application:
    name: club-service

  #  flyway:
  #    url: ${FLYWAY_URL}
  #    baseline-on-migrate: true
  #    enabled: true
  #    user: ${MYSQL_USERNAME}
  #    password: ${MYSQL_PASSWORD}

  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # ddl-auto: validate
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        show_sql: true
        format_sql: true

app:
  gateway:
    endpoint: https://gateway.gachdong.club

logging:
  level:
    org.hibernate.SQL: DEBUG
