springdoc:
  swagger-ui:
    urls[0]:
      name: "동아리 서비스"
      url: https://gateway-dev.gachdong.club/club/v3/api-docs
    urls[1]:
      name: "지원 서비스"
      url: https://gateway-dev.gachdong.club/application/v3/api-docs
    urls[2]:
      name: "인증/인가 서비스"
      url: https://gateway-dev.gachdong.club/auth/v3/api-docs

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-public
          uri: http://auth-service:8080
          predicates:
            - Path=/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}