springdoc:
  swagger-ui:
    enabled: true
    urls[0]:
      name: "동아리 서비스"
      url: https://gateway-dev.gachdong.club/club/v3/api-docs
    urls[1]:
      name: "지원 서비스"
      url: https://gateway-dev.gachdong.club/application/v3/api-docs
    urls[2]:
      name: "인증/인가 서비스"
      url: https://gateway-dev.gachdong.club/auth/v3/api-docs
    urls[3]:
      name: "사용자 서비스"
      url: https://gateway-dev.gachdong.club/user/v3/api-docs
    urls[4]:
      name: "알림 서비스"
      url: https://gateway-dev.gachdong.club/notification/v3/api-docs
    urls[5]:
      name: "어드민 서비스"
      url: https://gateway-dev.gachdong.club/admin/v3/api-docs

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
