spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    s3:
      bucket: ${bucket}
    region:
      static: ${region}
    stack:
      auto: false