app:
  gateway:
    endpoint: https://gateway-dev.gachdong.club

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
