app:
  gateway:
    endpoint: http://gateway-dev.gachdong.club

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
